name: Manage cloud infrastructure using github's own runner
on:
  push:
    branches:
      - main
      - dev

env:
  TERRAFORM_VERSION: 1.1.7

jobs:

  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate -no-color

  terraform-plan:
    runs-on: ubuntu-latest
    needs: [terraform-fmt, terraform-validate]
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform plan
        run: |
          terraform init
          terraform plan -out=tfplan
          ls

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
          if-no-files-found: error
          retention-days: 1

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: actions/download-artifact@v4
        with:
          name: tfplan
      - name: Terraform apply
        run: |
          ls
          terraform init
          terraform apply tfplan

